### ISSUE TITLE
Camera Permission on devices aksed every page reload

### ISSUE THREAD

**Issue by ilellouch** [werthdavid/ngx-scanner#45]
Hello,

I've integrated this component (Thanks) and  what I see today is : 
- On Desktop, permission is asked first time, then camera is working after each reload
- On mobile (I'm testing with Iphone SE, IOS 11 on Safari), everytime I'm reloading the page, same question over again "asking for permission".
Don't really know if it's a ngx-scanner question or a "permission handling by browser" question. Sorry if I'm mistaken.

Thanks
Ivan

**Comment by odahcam** [comment]
Different devices (browser) have some different behaviors. e.g.: Samsung Internet Browser asks for permissions everytime you choose a different camera. Chrome Browser in most Androids asks just the first time.

This is a difficult thing to track, so I will not close until @werthdavid gives his point.

Thanks for reporting. 😁

**Comment by werthdavid** [comment]
I did some research and it seems that you can't prevent Mobile Safari from asking, sorry for that.

But: [iOS 11.3](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_11_1.html#//apple_ref/doc/uid/TP40014305-CH14-SW1) has several changes regarding WebRTC, maybe the behavior changed there. I'll close the issue

**Comment by tillmon** [comment]
Try to turn off livereload
