### ISSUE TITLE
Typescript Error: Cannot redeclare block-scoped variable 'ngDevMode'.

### ISSUE THREAD

**Issue by olegkolner** [werthdavid/ngx-scanner#50]
I'm trying to integrate the ngx-scanner into my ionic-app. The appropriate package, as well as module dependencies, are installed. But nevertheless, I've got an error: 

"typescript: ...myproject/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts, line: 9
Cannot redeclare block-scoped variable 'ngDevMode'." 

My current angular version: 5.2.7

**Comment by odahcam** [comment]
Just update the package version. Duplicated: #34
